### ISSUE TITLE
Errors get logged, but impossible to catch

### ISSUE THREAD

**Issue by anselanza** [yoctopuce/yoctolib_ts#1]
I am using a pretty straightforward bit code based on https://github.com/yoctopuce/yoctolib_ts/blob/edbade80059efb8d8a9f90190954c538398879e5/example_nodejs/Doc-GettingStarted-Yocto-Light/demo.ts (TypeScript Yocto Light, NodeJS) and although everything works fine I would like to be able to handle errors, for example when the VirtualHub is not reachable for some reason.

Although the library logs a ton of errors, e.g. `ECONNREFUSED` and `WebSocket error:  ErrorEvent`, I cannot figure out how to handle these errors in my application, or even pick them up at at all!

For example, the following:
```
let errmsg: YErrorMsg = new YErrorMsg();
    if(await YAPI.RegisterHub('127.0.0.1', errmsg) != YAPI.SUCCESS) {
        console.log('Cannot contact VirtualHub on 127.0.0.1: '+errmsg.msg);
        return;
    }
```
Is actually unreachable code. The library apparently keeps trying to connect, logs plenty of errors to the console, but never actually
- throws an Error
- returns from `YAPI.RegisterHub` (with any return code)

Is there something I'm missing?

**Comment by yoctopuce** [comment]
The retries are not infinite, but repeat up to the timeout configured with YAPI.SetNetworkTimeout.
https://www.yoctopuce.com/EN/doc/reference/yoctolib-typescript-EN.html#YAPI.SetNetworkTimeout
RegisterHub retries even if the error is ECONNREFUSED, which may look useless at first sight, but it is actually very helpful, for instance when designing a system made of multiple appliances which may not power up in the most convenient order after a power cut. Even when your service is simply trying to connect to the VirtualHub service, allowing a few seconds for the VirtualHub service to come up will secure a proper startup when the machine starts up.

The default value for the Network timeout is 20s. I have just verified on the published version of the code, and you do receive an exception after the 20s timeout as designed. If you prefer to receive an error code than getting an exception, call YAPI.DisableExceptions before:
https://www.yoctopuce.com/EN/doc/reference/yoctolib-typescript-EN.html#YAPI.DisableExceptions

If you just want to check if the service is available, rather than changing the NetworkTimeout you can also use the TestHub method which takes an extra argument corresponding to the desired connection timeout.
https://www.yoctopuce.com/EN/doc/reference/yoctolib-typescript-EN.html#YAPI.TestHub

**Comment by anselanza** [comment]
I don't think this is an entirely satisfactory solution. It still means that the client application has to wait for a timeout before any error (whether exception or an error code doesn't matter too much) can be received. Why not throw the error before having to wait for the timeout?

**Comment by yoctopuce** [comment]
If you want to know immediately if the hub is reachable, simply use TestHub with a 20ms timeout for instance.

You would typically use RegisterHub when you are expecting your hub to be reachable and that it is worth waiting for it (for the time of your choice) rather than failing the whole process.

**Comment by anselanza** [comment]
Makes sense. Thank you for responding!
